import React, { useState, useMemo } from 'react';
import {
  ShoppingCart, AlertTriangle, Plus, CheckCircle, Clock, Package, X, Zap, TrendingUp, Truck
} from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';
import { GlowCard } from '@/components/common/GlowCard';
import { StatusBadge } from '@/components/common/StatusBadge';
import { cn } from '@/lib/utils';
import { getSuggestedPurchaseQty, getFutureDemand, recommendSupplier } from '@/utils/helpers';

export const PurchasePanel: React.FC = () => {
  const materials = useAppStore(s => s.materials);
  const suppliers = useAppStore(s => s.suppliers);
  const purchaseRequests = useAppStore(s => s.purchaseRequests);
  const createPurchaseRequest = useAppStore(s => s.createPurchaseRequest);
  const approvePurchase = useAppStore(s => s.approvePurchase);
  const currentUser = useAppStore(s => s.currentUser);

  const [selectedMaterialId, setSelectedMaterialId] = useState('');
  const [quantity, setQuantity] = useState('');
  const [reason, setReason] = useState('');
  const [showForm, setShowForm] = useState(false);

  const lowStockMaterials = materials.filter(m => m.stock < m.safetyThreshold);
  const pendingRequests = purchaseRequests.filter(p => p.status === 'pending');
  const autoPendingRequests = pendingRequests.filter(p => (p as any).isAutoGenerated);

  const canCreate = currentUser && ['worker', 'inspector', 'manager', 'director'].includes(currentUser.role);
  const canApprove = currentUser && ['manager', 'director'].includes(currentUser.role);

  const demandPreview = useMemo(() => getFutureDemand(), []);
  const demand7DayTotal = useMemo(() => demandPreview.reduce((s, d) => s + d.demand, 0), [demandPreview]);

  const handleMaterialChange = (id: string) => {
    setSelectedMaterialId(id);
    const mat = materials.find(m => m.id === id);
    if (mat) {
      const suggested = getSuggestedPurchaseQty(mat.stock, mat.safetyThreshold, mat.unit);
      setQuantity(String(suggested.qty));
      setReason(suggested.reason);
    }
  };

  const handleQuickAutoPurchase = (materialId: string) => {
    const mat = materials.find(m => m.id === materialId);
    if (!mat) return;
    const suggested = getSuggestedPurchaseQty(mat.stock, mat.safetyThreshold, mat.unit);
    createPurchaseRequest(materialId, suggested.qty, suggested.reason, true);
  };

  const handleSubmit = () => {
    if (!selectedMaterialId || !quantity || !reason) return;
    createPurchaseRequest(selectedMaterialId, parseInt(quantity), reason);
    setSelectedMaterialId('');
    setQuantity('');
    setReason('');
    setShowForm(false);
  };

  return (
    <GlowCard className="w-96 h-full flex flex-col gap-3 overflow-y-auto" color="green">
      <div className="flex items-center gap-2">
        <ShoppingCart className="w-5 h-5 text-neon-green" />
        <h3 className="text-sm font-bold text-neon-green glow-text-green">采购申请管理</h3>
        {autoPendingRequests.length > 0 && (
          <span className="ml-1 px-1.5 py-0.5 rounded bg-neon-orange/20 border border-neon-orange/40 text-neon-orange text-[9px] font-medium flex items-center gap-0.5">
            <Zap className="w-2.5 h-2.5" />
            {autoPendingRequests.length}条自动申请
          </span>
        )}
        <button
          onClick={() => setShowForm(!showForm)}
          className={cn(
            'ml-auto w-7 h-7 rounded-md flex items-center justify-center transition-colors',
            showForm
              ? 'bg-neon-red/20 border border-neon-red/50 text-neon-red'
              : 'bg-neon-green/20 border border-neon-green/50 text-neon-green hover:bg-neon-green/30'
          )}
        >
          {showForm ? <X className="w-4 h-4" /> : <Plus className="w-4 h-4" />}
        </button>
      </div>

      {showForm && canCreate && (
        <GlowCard className="p-3 space-y-2.5" color="blue">
          <div className="text-xs font-medium text-neon-blue flex items-center gap-1">
            <Plus className="w-3.5 h-3.5" />
            新建采购申请
          </div>
          <div>
            <div className="text-[10px] text-white/50 mb-1">选择物料</div>
            <select
              value={selectedMaterialId}
              onChange={(e) => handleMaterialChange(e.target.value)}
              className="w-full px-2 py-1.5 rounded-md bg-white/5 border border-white/10 text-xs text-white focus:outline-none focus:border-neon-green/50"
            >
              <option value="">-- 请选择物料 --</option>
              {materials.map(m => (
                <option key={m.id} value={m.id}>
                  {m.name} (库存:{m.stock}{m.unit}, 阈值:{m.safetyThreshold}{m.unit})
                </option>
              ))}
            </select>
          </div>
          <div>
            <div className="text-[10px] text-white/50 mb-1 flex items-center justify-between">
              <span>申请数量</span>
              {selectedMaterialId && (
                <span className="text-neon-green">系统建议: {quantity || '-'}</span>
              )}
            </div>
            <input
              type="number"
              value={quantity}
              onChange={(e) => setQuantity(e.target.value)}
              placeholder="请输入数量"
              min="1"
              className="w-full px-2 py-1.5 rounded-md bg-white/5 border border-white/10 text-xs text-white placeholder-white/30 focus:outline-none focus:border-neon-green/50"
            />
          </div>
          <div>
            <div className="text-[10px] text-white/50 mb-1">申请原因</div>
            <textarea
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              placeholder="请输入申请原因..."
              className="w-full h-14 px-2 py-1.5 rounded-md bg-white/5 border border-white/10 text-xs text-white placeholder-white/30 focus:outline-none focus:border-neon-green/50 resize-none"
            />
          </div>
          <button
            onClick={handleSubmit}
            disabled={!selectedMaterialId || !quantity || !reason}
            className="w-full py-1.5 rounded-md bg-neon-green/20 border border-neon-green/50 text-neon-green text-xs font-medium hover:bg-neon-green/30 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            提交申请
          </button>
        </GlowCard>
      )}

      <div className="space-y-2">
        <div className="text-xs text-white/60 flex items-center justify-between">
          <div className="flex items-center gap-1">
            <AlertTriangle className="w-3 h-3 text-neon-yellow" />
            低库存预警 ({lowStockMaterials.length})
          </div>
          <div className="flex items-center gap-1 text-neon-blue">
            <TrendingUp className="w-3 h-3" />
            7日总需求: {demand7DayTotal}
          </div>
        </div>
        <div className="space-y-1.5 max-h-44 overflow-y-auto">
          {lowStockMaterials.map(m => {
            const suggested = getSuggestedPurchaseQty(m.stock, m.safetyThreshold, m.unit);
            const hasAutoRequest = pendingRequests.some(
              p => p.materialId === m.id && (p as any).isAutoGenerated
            );
            return (
              <div key={m.id} className="p-2.5 rounded-md bg-neon-yellow/5 border border-neon-yellow/20">
                <div className="flex items-center justify-between mb-1">
                  <div className="text-xs text-white font-medium">{m.name}</div>
                  <div className="text-[10px] text-neon-orange font-mono">建议采购: {suggested.qty}{m.unit}<span className="text-white/40 ml-1">7日需求: {suggested.demandTotal}{m.unit}</span></div>
                </div>
                <div className="flex items-center justify-between mb-1.5">
                  <div className="text-[10px] text-white/50 font-mono">
                    当前: {m.stock}/{m.safetyThreshold} {m.unit}
                  </div>
                  <div className="w-16 h-1.5 rounded-full bg-white/10 overflow-hidden">
                    <div
                      className="h-full bg-neon-yellow rounded-full"
                      style={{ width: `${Math.min(100, (m.stock / m.safetyThreshold) * 100)}%` }}
                    />
                  </div>
                </div>
                <div className="text-[10px] text-white/40 mb-1.5">{suggested.reason}</div>
                {canCreate && !hasAutoRequest ? (
                  <button
                    onClick={() => handleQuickAutoPurchase(m.id)}
                    className="w-full flex items-center justify-center gap-1 py-1 rounded-md bg-neon-green/20 border border-neon-green/40 text-neon-green text-[10px] font-medium hover:bg-neon-green/30 transition-colors"
                  >
                    <Zap className="w-2.5 h-2.5" />
                    按建议量自动生成申请
                  </button>
                ) : hasAutoRequest ? (
                  <div className="w-full py-1 text-center text-[10px] text-neon-blue">✓ 已自动生成采购申请，待审批</div>
                ) : null}
              </div>
            );
          })}
          {lowStockMaterials.length === 0 && (
            <div className="text-[11px] text-white/30 text-center py-2">暂无低库存物料，所有库存充足</div>
          )}
        </div>
      </div>

      <div className="space-y-2 flex-1 overflow-y-auto">
        <div className="text-xs text-white/60 flex items-center gap-1">
          <Clock className="w-3 h-3" />
          待审批申请 ({pendingRequests.length})
        </div>
        <div className="space-y-1.5">
          {pendingRequests.map(pr => {
            const mat = materials.find(m => m.id === pr.materialId);
            const isAuto = (pr as any).isAutoGenerated;
            return (
              <div key={pr.id} className={cn(
                'p-2.5 rounded-md border',
                isAuto
                  ? 'bg-neon-orange/5 border-neon-orange/20'
                  : 'bg-white/5 border-white/10'
              )}>
                <div className="flex items-center justify-between mb-1.5">
                  <div className="flex items-center gap-1.5">
                    <Package className={cn('w-3.5 h-3.5', isAuto ? 'text-neon-orange' : 'text-neon-blue')} />
                    <span className="text-xs text-white font-medium">{mat?.name || pr.materialId}</span>
                    {isAuto && (
                      <span className="px-1 py-0.5 rounded bg-neon-orange/20 text-neon-orange text-[9px] flex items-center gap-0.5">
                        <Zap className="w-2 h-2" />
                        自动
                      </span>
                    )}
                  </div>
                  <StatusBadge status="blue" text={'数量: ' + pr.quantity} className="text-[9px]" />
                </div>
                <div className="text-[10px] text-white/60 mb-1.5 line-clamp-2">{pr.reason}</div>
                {pr.recommendedSupplierId && (
                  <div className="mb-1.5 p-1.5 rounded-md bg-neon-blue/5 border border-neon-blue/15">
                    <div className="flex items-center gap-1 mb-0.5">
                      <Truck className="w-3 h-3 text-neon-blue" />
                      <span className="text-[10px] text-neon-blue font-medium">推荐供应商: {suppliers.find(s => s.id === pr.recommendedSupplierId)?.name || pr.recommendedSupplierId}</span>
                    </div>
                    {pr.recommendedSupplierReason && (
                      <div className="text-[10px] text-white/50 pl-4">推荐理由: {pr.recommendedSupplierReason}</div>
                    )}
                    {pr.estimatedArrival && (
                      <div className="text-[10px] text-white/50 pl-4">预计到货: {pr.estimatedArrival}</div>
                    )}
                  </div>
                )}
                <div className="flex items-center justify-between">
                  <div className="text-[10px] text-white/40 font-mono">{pr.createdAt}</div>
                  {canApprove && (
                    <button
                      onClick={() => approvePurchase(pr.id)}
                      className="flex items-center gap-1 px-2 py-0.5 rounded-md bg-neon-green/20 border border-neon-green/50 text-neon-green text-[10px] font-medium hover:bg-neon-green/30 transition-colors"
                    >
                      <CheckCircle className="w-3 h-3" />
                      批准
                    </button>
                  )}
                </div>
              </div>
            );
          })}
          {pendingRequests.length === 0 && (
            <div className="text-[11px] text-white/30 text-center py-4">暂无待审批申请</div>
          )}
        </div>
      </div>
    </GlowCard>
  );
};
