import React, { useState, useMemo } from 'react';
import {
  ShoppingCart, AlertTriangle, Plus, CheckCircle, Clock, Package, X, Zap, TrendingUp, Truck, ChevronDown, ChevronRight, Calendar
} from 'lucide-react';
import { useAppStore } from '@/store/useAppStore';
import { GlowCard } from '@/components/common/GlowCard';
import { StatusBadge } from '@/components/common/StatusBadge';
import { cn } from '@/lib/utils';
import { getSuggestedPurchaseQty, getFutureDemand } from '@/utils/helpers';
import type { SupplierAlternative } from '@/types';

export const PurchasePanel: React.FC = () => {
  const materials = useAppStore(s => s.materials);
  const suppliers = useAppStore(s => s.suppliers);
  const purchaseRequests = useAppStore(s => s.purchaseRequests);
  const createPurchaseRequest = useAppStore(s => s.createPurchaseRequest);
  const approvePurchase = useAppStore(s => s.approvePurchase);
  const confirmDelivery = useAppStore(s => s.confirmDelivery);
  const currentUser = useAppStore(s => s.currentUser);

  const [selectedMaterialId, setSelectedMaterialId] = useState('');
  const [quantity, setQuantity] = useState('');
  const [reason, setReason] = useState('');
  const [showForm, setShowForm] = useState(false);
  const [selectedSupplierIds, setSelectedSupplierIds] = useState<Record<string, string>>({});
  const [deliveryForms, setDeliveryForms] = useState<Record<string, { actualQuantity: string; deliveryDate: string; inspectionResult: 'pass' | 'fail' | 'pending'; batchNo: string }>>({});
  const [deliveryFormErrors, setDeliveryFormErrors] = useState<Record<string, { actualQuantity?: string; deliveryDate?: string }>>({});
  const [showDelivered, setShowDelivered] = useState(false);

  const lowStockMaterials = materials.filter(m => (m.stock - m.lockedStock) < m.safetyThreshold);
  const pendingRequests = purchaseRequests.filter(p => p.status === 'pending');
  const deliveringRequests = purchaseRequests.filter(p => p.status === 'delivering');
  const deliveredRequests = purchaseRequests.filter(p => p.status === 'delivered');
  const autoPendingRequests = pendingRequests.filter(p => (p as any).isAutoGenerated);

  const canCreate = currentUser && ['worker', 'inspector', 'manager', 'director'].includes(currentUser.role);
  const canApprove = currentUser && ['manager', 'director'].includes(currentUser.role);

  const demandPreview = useMemo(() => getFutureDemand(), []);
  const demand7DayTotal = useMemo(() => demandPreview.reduce((s, d) => s + d.demand, 0), [demandPreview]);

  const todayStr = useMemo(() => {
    const d = new Date();
    const pad = (n: number) => n.toString().padStart(2, '0');
    return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}`;
  }, []);

  const handleMaterialChange = (id: string) => {
    setSelectedMaterialId(id);
    const mat = materials.find(m => m.id === id);
    if (mat) {
      const suggested = getSuggestedPurchaseQty(mat.stock - mat.lockedStock, mat.safetyThreshold, mat.unit);
      setQuantity(String(suggested.qty));
      setReason(suggested.reason);
    }
  };

  const handleQuickAutoPurchase = (materialId: string) => {
    const mat = materials.find(m => m.id === materialId);
    if (!mat) return;
    const suggested = getSuggestedPurchaseQty(mat.stock - mat.lockedStock, mat.safetyThreshold, mat.unit);
    createPurchaseRequest(materialId, suggested.qty, suggested.reason, true);
  };

  const handleSubmit = () => {
    if (!selectedMaterialId || !quantity || !reason) return;
    createPurchaseRequest(selectedMaterialId, parseInt(quantity), reason);
    setSelectedMaterialId('');
    setQuantity('');
    setReason('');
    setShowForm(false);
  };

  const handleApprove = (prId: string) => {
    approvePurchase(prId, selectedSupplierIds[prId]);
  };

  const handleConfirmDelivery = (prId: string) => {
    const form = deliveryForms[prId];
    if (!form) return;

    const errors: { actualQuantity?: string; deliveryDate?: string } = {};
    const qtyNum = parseFloat(form.actualQuantity);
    if (!form.actualQuantity || isNaN(qtyNum) || qtyNum <= 0) {
      errors.actualQuantity = '请输入有效的实收数量（必须大于0）';
    }
    if (!form.deliveryDate) {
      errors.deliveryDate = '请选择到货日期';
    }

    setDeliveryFormErrors(prev => ({ ...prev, [prId]: errors }));

    if (Object.keys(errors).length > 0) return;

    confirmDelivery(prId, qtyNum, form.deliveryDate, form.inspectionResult, form.batchNo || undefined);
  };

  const getDeliveryForm = (prId: string, defaultQty: number) => {
    return deliveryForms[prId] || { actualQuantity: String(defaultQty), deliveryDate: todayStr, inspectionResult: 'pending' as const, batchNo: '' };
  };

  return (
    <GlowCard className="w-96 h-full flex flex-col gap-3 overflow-y-auto" color="green">
      <div className="flex items-center gap-2">
        <ShoppingCart className="w-5 h-5 text-neon-green" />
        <h3 className="text-sm font-bold text-neon-green glow-text-green">采购申请管理</h3>
        {autoPendingRequests.length > 0 && (
          <span className="ml-1 px-1.5 py-0.5 rounded bg-neon-orange/20 border border-neon-orange/40 text-neon-orange text-[9px] font-medium flex items-center gap-0.5">
            <Zap className="w-2.5 h-2.5" />
            {autoPendingRequests.length}条自动申请
          </span>
        )}
        <button
          onClick={() => setShowForm(!showForm)}
          className={cn(
            'ml-auto w-7 h-7 rounded-md flex items-center justify-center transition-colors',
            showForm
              ? 'bg-neon-red/20 border border-neon-red/50 text-neon-red'
              : 'bg-neon-green/20 border border-neon-green/50 text-neon-green hover:bg-neon-green/30'
          )}
        >
          {showForm ? <X className="w-4 h-4" /> : <Plus className="w-4 h-4" />}
        </button>
      </div>

      {showForm && canCreate && (
        <GlowCard className="p-3 space-y-2.5" color="blue">
          <div className="text-xs font-medium text-neon-blue flex items-center gap-1">
            <Plus className="w-3.5 h-3.5" />
            新建采购申请
          </div>
          <div>
            <div className="text-[10px] text-white/50 mb-1">选择物料</div>
            <select
              value={selectedMaterialId}
              onChange={(e) => handleMaterialChange(e.target.value)}
              className="w-full px-2 py-1.5 rounded-md bg-white/5 border border-white/10 text-xs text-white focus:outline-none focus:border-neon-green/50"
            >
              <option value="">-- 请选择物料 --</option>
              {materials.map(m => (
                <option key={m.id} value={m.id}>
                  {m.name} (可用:{m.stock - m.lockedStock}{m.unit}, 阈值:{m.safetyThreshold}{m.unit})
                </option>
              ))}
            </select>
          </div>
          <div>
            <div className="text-[10px] text-white/50 mb-1 flex items-center justify-between">
              <span>申请数量</span>
              {selectedMaterialId && (
                <span className="text-neon-green">系统建议: {quantity || '-'}</span>
              )}
            </div>
            <input
              type="number"
              value={quantity}
              onChange={(e) => setQuantity(e.target.value)}
              placeholder="请输入数量"
              min="1"
              className="w-full px-2 py-1.5 rounded-md bg-white/5 border border-white/10 text-xs text-white placeholder-white/30 focus:outline-none focus:border-neon-green/50"
            />
          </div>
          <div>
            <div className="text-[10px] text-white/50 mb-1">申请原因</div>
            <textarea
              value={reason}
              onChange={(e) => setReason(e.target.value)}
              placeholder="请输入申请原因..."
              className="w-full h-14 px-2 py-1.5 rounded-md bg-white/5 border border-white/10 text-xs text-white placeholder-white/30 focus:outline-none focus:border-neon-green/50 resize-none"
            />
          </div>
          <button
            onClick={handleSubmit}
            disabled={!selectedMaterialId || !quantity || !reason}
            className="w-full py-1.5 rounded-md bg-neon-green/20 border border-neon-green/50 text-neon-green text-xs font-medium hover:bg-neon-green/30 transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
          >
            提交申请
          </button>
        </GlowCard>
      )}

      <div className="space-y-2">
        <div className="text-xs text-white/60 flex items-center justify-between">
          <div className="flex items-center gap-1">
            <AlertTriangle className="w-3 h-3 text-neon-yellow" />
            低库存预警 ({lowStockMaterials.length})
          </div>
          <div className="flex items-center gap-1 text-neon-blue">
            <TrendingUp className="w-3 h-3" />
            7日总需求: {demand7DayTotal}
          </div>
        </div>
        <div className="space-y-1.5 max-h-44 overflow-y-auto">
          {lowStockMaterials.map(m => {
            const suggested = getSuggestedPurchaseQty(m.stock - m.lockedStock, m.safetyThreshold, m.unit);
            const hasAutoRequest = pendingRequests.some(
              p => p.materialId === m.id && (p as any).isAutoGenerated
            );
            const availableStock = m.stock - m.lockedStock;
            return (
              <div key={m.id} className="p-2.5 rounded-md bg-neon-yellow/5 border border-neon-yellow/20">
                <div className="flex items-center justify-between mb-1">
                  <div className="text-xs text-white font-medium">{m.name}</div>
                  <div className="text-[10px] text-neon-orange font-mono">建议采购: {suggested.qty}{m.unit}<span className="text-white/40 ml-1">7日需求: {suggested.demandTotal}{m.unit}</span></div>
                </div>
                <div className="flex items-center justify-between mb-1.5">
                  <div className="text-[10px] text-white/50 font-mono flex items-center gap-2">
                    <span>可用: {availableStock}/{m.safetyThreshold} {m.unit}</span>
                    {m.lockedStock > 0 && (
                      <span className="text-neon-red">锁定: {m.lockedStock}</span>
                    )}
                  </div>
                  <div className="w-16 h-1.5 rounded-full bg-white/10 overflow-hidden">
                    <div
                      className="h-full bg-neon-yellow rounded-full"
                      style={{ width: `${Math.min(100, (availableStock / m.safetyThreshold) * 100)}%` }}
                    />
                  </div>
                </div>
                <div className="text-[10px] text-white/40 mb-1.5">{suggested.reason}</div>
                {canCreate && !hasAutoRequest ? (
                  <button
                    onClick={() => handleQuickAutoPurchase(m.id)}
                    className="w-full flex items-center justify-center gap-1 py-1 rounded-md bg-neon-green/20 border border-neon-green/40 text-neon-green text-[10px] font-medium hover:bg-neon-green/30 transition-colors"
                  >
                    <Zap className="w-2.5 h-2.5" />
                    按建议量自动生成申请
                  </button>
                ) : hasAutoRequest ? (
                  <div className="w-full py-1 text-center text-[10px] text-neon-blue">✓ 已自动生成采购申请，待审批</div>
                ) : null}
              </div>
            );
          })}
          {lowStockMaterials.length === 0 && (
            <div className="text-[11px] text-white/30 text-center py-2">暂无低库存物料，所有库存充足</div>
          )}
        </div>
      </div>

      <div className="space-y-2 flex-1 overflow-y-auto">
        <div className="text-xs text-white/60 flex items-center gap-1">
          <Clock className="w-3 h-3" />
          待审批申请 ({pendingRequests.length})
        </div>
        <div className="space-y-1.5">
          {pendingRequests.map(pr => {
            const mat = materials.find(m => m.id === pr.materialId);
            const isAuto = (pr as any).isAutoGenerated;
            const alternatives: SupplierAlternative[] = pr.supplierAlternatives || [];
            const selectedSup = selectedSupplierIds[pr.id] || pr.recommendedSupplierId || '';
            return (
              <div key={pr.id} className={cn(
                'p-2.5 rounded-md border',
                isAuto
                  ? 'bg-neon-orange/5 border-neon-orange/20'
                  : 'bg-white/5 border-white/10'
              )}>
                <div className="flex items-center justify-between mb-1.5">
                  <div className="flex items-center gap-1.5">
                    <Package className={cn('w-3.5 h-3.5', isAuto ? 'text-neon-orange' : 'text-neon-blue')} />
                    <span className="text-xs text-white font-medium">{mat?.name || pr.materialId}</span>
                    {isAuto && (
                      <span className="px-1 py-0.5 rounded bg-neon-orange/20 text-neon-orange text-[9px] flex items-center gap-0.5">
                        <Zap className="w-2 h-2" />
                        自动
                      </span>
                    )}
                  </div>
                  <StatusBadge status="blue" text={'数量: ' + pr.quantity} className="text-[9px]" />
                </div>
                <div className="text-[10px] text-white/60 mb-1.5 line-clamp-2">{pr.reason}</div>
                {pr.recommendedSupplierId && alternatives.length === 0 && (
                  <div className="mb-1.5 p-1.5 rounded-md bg-neon-blue/5 border border-neon-blue/15">
                    <div className="flex items-center gap-1 mb-0.5">
                      <Truck className="w-3 h-3 text-neon-blue" />
                      <span className="text-[10px] text-neon-blue font-medium">推荐供应商: {suppliers.find(s => s.id === pr.recommendedSupplierId)?.name || pr.recommendedSupplierId}</span>
                    </div>
                    {pr.recommendedSupplierReason && (
                      <div className="text-[10px] text-white/50 pl-4">推荐理由: {pr.recommendedSupplierReason}</div>
                    )}
                    {pr.estimatedArrival && (
                      <div className="text-[10px] text-white/50 pl-4">预计到货: {pr.estimatedArrival}</div>
                    )}
                  </div>
                )}
                {alternatives.length > 0 && (
                  <div className="mb-1.5 p-1.5 rounded-md bg-neon-blue/5 border border-neon-blue/15">
                    <div className="flex items-center gap-1 mb-1">
                      <Truck className="w-3 h-3 text-neon-blue" />
                      <span className="text-[10px] text-neon-blue font-medium">供应商对比</span>
                    </div>
                    <table className="w-full text-[9px]">
                      <thead>
                        <tr className="text-white/40 border-b border-white/10">
                          <th className="py-0.5 text-left font-normal w-4"></th>
                          <th className="py-0.5 text-left font-normal">供应商</th>
                          <th className="py-0.5 text-center font-normal">评分</th>
                          <th className="py-0.5 text-center font-normal">交期</th>
                          <th className="py-0.5 text-center font-normal">单价</th>
                          <th className="py-0.5 text-center font-normal">不合格</th>
                          <th className="py-0.5 text-center font-normal">预计到货</th>
                        </tr>
                      </thead>
                      <tbody>
                        {alternatives.map(alt => {
                          const isRecommended = alt.supplierId === pr.recommendedSupplierId;
                          const isSelected = alt.supplierId === selectedSup;
                          return (
                            <tr
                              key={alt.supplierId}
                              className={cn(
                                'border-b border-white/5',
                                isRecommended && 'bg-neon-green/5',
                                isSelected && 'ring-1 ring-neon-green/30'
                              )}
                            >
                              <td className="py-0.5">
                                <input
                                  type="radio"
                                  name={`supplier-${pr.id}`}
                                  checked={isSelected}
                                  onChange={() => setSelectedSupplierIds(prev => ({ ...prev, [pr.id]: alt.supplierId }))}
                                  className="w-2.5 h-2.5 accent-neon-green"
                                />
                              </td>
                              <td className={cn('py-0.5', isRecommended ? 'text-neon-green font-medium' : 'text-white/70')}>
                                {alt.supplierName}{isRecommended && ' ★'}
                              </td>
                              <td className="py-0.5 text-center text-white/60">{alt.score}</td>
                              <td className="py-0.5 text-center text-white/60">{alt.leadTime}天</td>
                              <td className="py-0.5 text-center text-white/60">{alt.unitPrice}/{alt.priceUnit}</td>
                              <td className={cn('py-0.5 text-center', alt.failCount > 0 ? 'text-neon-red' : 'text-white/60')}>{alt.failCount}</td>
                              <td className="py-0.5 text-center text-white/60">{alt.estimatedArrival}</td>
                            </tr>
                          );
                        })}
                      </tbody>
                    </table>
                  </div>
                )}
                <div className="flex items-center justify-between">
                  <div className="text-[10px] text-white/40 font-mono">{pr.createdAt}</div>
                  {canApprove && (
                    <button
                      onClick={() => handleApprove(pr.id)}
                      className="flex items-center gap-1 px-2 py-0.5 rounded-md bg-neon-green/20 border border-neon-green/50 text-neon-green text-[10px] font-medium hover:bg-neon-green/30 transition-colors"
                    >
                      <CheckCircle className="w-3 h-3" />
                      批准
                    </button>
                  )}
                </div>
              </div>
            );
          })}
          {pendingRequests.length === 0 && (
            <div className="text-[11px] text-white/30 text-center py-4">暂无待审批申请</div>
          )}
        </div>
      </div>

      {deliveringRequests.length > 0 && (
        <div className="space-y-2">
          <div className="text-xs text-white/60 flex items-center gap-1">
            <Truck className="w-3 h-3 text-neon-blue" />
            待到货 ({deliveringRequests.length})
          </div>
          <div className="space-y-1.5">
            {deliveringRequests.map(pr => {
              const mat = materials.find(m => m.id === pr.materialId);
              const supplierId = pr.confirmedSupplierId || pr.recommendedSupplierId;
              const supplier = suppliers.find(s => s.id === supplierId);
              const form = getDeliveryForm(pr.id, pr.quantity);
              return (
                <div key={pr.id} className="p-2.5 rounded-md bg-neon-blue/5 border border-neon-blue/20">
                  <div className="flex items-center justify-between mb-1.5">
                    <div className="flex items-center gap-1.5">
                      <Package className="w-3.5 h-3.5 text-neon-blue" />
                      <span className="text-xs text-white font-medium">{mat?.name || pr.materialId}</span>
                      <StatusBadge status="blue" text={'数量: ' + pr.quantity} className="text-[9px]" />
                    </div>
                  </div>
                  <div className="text-[10px] text-white/60 mb-1 line-clamp-2">{pr.reason}</div>
                  <div className="flex items-center gap-3 mb-1.5 text-[10px]">
                    {supplier && (
                      <div className="flex items-center gap-1 text-neon-blue">
                        <Truck className="w-3 h-3" />
                        <span>{supplier.name}</span>
                      </div>
                    )}
                    {pr.estimatedArrival && (
                      <div className="flex items-center gap-1 text-neon-yellow">
                        <Calendar className="w-3 h-3" />
                        <span>预计到货: {pr.estimatedArrival}</span>
                      </div>
                    )}
                  </div>
                  <div className="p-2 rounded-md bg-white/5 border border-white/10 space-y-1.5">
                    <div className="text-[10px] text-neon-green font-medium mb-1">确认到货</div>
                    <div className="flex items-center gap-2">
                      <div className="flex-1">
                        <div className="text-[9px] text-white/40 mb-0.5">实际数量</div>
                        <input
                          type="number"
                          value={form.actualQuantity}
                          onChange={(e) => setDeliveryForms(prev => ({
                            ...prev,
                            [pr.id]: { ...getDeliveryForm(pr.id, pr.quantity), actualQuantity: e.target.value }
                          }))}
                          min="0"
                          className={cn(
                            "w-full px-1.5 py-1 rounded bg-white/5 border text-[10px] text-white focus:outline-none focus:border-neon-green/50",
                            deliveryFormErrors[pr.id]?.actualQuantity ? 'border-neon-red/50' : 'border-white/10'
                          )}
                        />
                        {deliveryFormErrors[pr.id]?.actualQuantity && (
                          <div className="text-[9px] text-neon-red mt-0.5">{deliveryFormErrors[pr.id].actualQuantity}</div>
                        )}
                      </div>
                      <div className="flex-1">
                        <div className="text-[9px] text-white/40 mb-0.5">到货日期</div>
                        <input
                          type="date"
                          value={form.deliveryDate}
                          onChange={(e) => setDeliveryForms(prev => ({
                            ...prev,
                            [pr.id]: { ...getDeliveryForm(pr.id, pr.quantity), deliveryDate: e.target.value }
                          }))}
                          className={cn(
                            "w-full px-1.5 py-1 rounded bg-white/5 border text-[10px] text-white focus:outline-none focus:border-neon-green/50",
                            deliveryFormErrors[pr.id]?.deliveryDate ? 'border-neon-red/50' : 'border-white/10'
                          )}
                        />
                        {deliveryFormErrors[pr.id]?.deliveryDate && (
                          <div className="text-[9px] text-neon-red mt-0.5">{deliveryFormErrors[pr.id].deliveryDate}</div>
                        )}
                      </div>
                    </div>
                    <div className="flex items-center gap-2">
                      <div className="flex-1">
                        <div className="text-[9px] text-white/40 mb-0.5">检验结果</div>
                        <select
                          value={form.inspectionResult}
                          onChange={(e) => setDeliveryForms(prev => ({
                            ...prev,
                            [pr.id]: { ...getDeliveryForm(pr.id, pr.quantity), inspectionResult: e.target.value as 'pass' | 'fail' | 'pending' }
                          }))}
                          className="w-full px-1.5 py-1 rounded bg-white/5 border border-white/10 text-[10px] text-white focus:outline-none focus:border-neon-green/50"
                        >
                          <option value="pending">待检</option>
                          <option value="pass">合格</option>
                          <option value="fail">不合格</option>
                        </select>
                      </div>
                      <div className="flex-1">
                        <div className="text-[9px] text-white/40 mb-0.5">批次号</div>
                        <input
                          type="text"
                          value={form.batchNo}
                          onChange={(e) => setDeliveryForms(prev => ({
                            ...prev,
                            [pr.id]: { ...getDeliveryForm(pr.id, pr.quantity), batchNo: e.target.value }
                          }))}
                          placeholder="留空自动生成"
                          className="w-full px-1.5 py-1 rounded bg-white/5 border border-white/10 text-[10px] text-white placeholder-white/30 focus:outline-none focus:border-neon-green/50"
                        />
                      </div>
                    </div>
                    <button
                      onClick={() => handleConfirmDelivery(pr.id)}
                      className="w-full py-1 rounded-md bg-neon-green/20 border border-neon-green/50 text-neon-green text-[10px] font-medium hover:bg-neon-green/30 transition-colors"
                    >
                      确认到货
                    </button>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {deliveredRequests.length > 0 && (
        <div>
          <button
            onClick={() => setShowDelivered(!showDelivered)}
            className="w-full flex items-center justify-between py-1.5 px-2 rounded-md bg-white/5 border border-white/10 text-xs text-white/50 hover:bg-white/10 transition-colors"
          >
            <div className="flex items-center gap-1.5">
              <CheckCircle className="w-3 h-3 text-neon-green" />
              已到货 ({deliveredRequests.length})
            </div>
            {showDelivered ? <ChevronDown className="w-3 h-3" /> : <ChevronRight className="w-3 h-3" />}
          </button>
          {showDelivered && (
            <div className="mt-1.5 space-y-1">
              {deliveredRequests.map(pr => {
                const mat = materials.find(m => m.id === pr.materialId);
                return (
                  <div key={pr.id} className="p-2 rounded-md bg-neon-green/5 border border-neon-green/15">
                    <div className="flex items-center justify-between">
                      <div className="flex items-center gap-1.5">
                        <Package className="w-3 h-3 text-neon-green" />
                        <span className="text-[10px] text-white/70">{mat?.name || pr.materialId}</span>
                      </div>
                      <div className="text-[9px] text-white/40">
                        {pr.actualQuantity != null ? `${pr.actualQuantity}` : `${pr.quantity}`} → {pr.deliveryDate || '-'}
                      </div>
                    </div>
                    {pr.deliveryInspectionResult && (
                      <div className={cn(
                        'mt-0.5 text-[9px]',
                        pr.deliveryInspectionResult === 'pass' ? 'text-neon-green' :
                        pr.deliveryInspectionResult === 'fail' ? 'text-neon-red' : 'text-neon-yellow'
                      )}>
                        {pr.deliveryInspectionResult === 'pass' ? '合格' : pr.deliveryInspectionResult === 'fail' ? '不合格' : '待检'}
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          )}
        </div>
      )}
    </GlowCard>
  );
};
